version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/pillyProject
    overwrite: true
permission:
  - object: /home/ec2-user/pillyProject/
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart:
    - location: /home/ec2-user/pillyProject/scripts/deploy.sh
      timeout: 60
      runas: ec2-user